defaultEntryPoints = ["http"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http
[entryPoints]
  [entryPoints.http]
  address = ":80"

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedbydefault = false
